version: '3.4'

services:
  sotogomeztelesforo.alumno.service:
    image: ${DOCKER_REGISTRY-}sotogomeztelesforoalumnoservice
    container_name: sgt.school.service
    build:
      context: .
      dockerfile: backend/Domain/School/SotoGomezTelesforo.Alumno.Service/Dockerfile
    ports:
      - 9091:80
      - 9092:443
    networks:
      - backend

  sotogomeztelesforo.security.service:
    image: ${DOCKER_REGISTRY-}sotogomeztelesforosecurityservice
    container_name: sgt.security.service
    build:
      context: .
      dockerfile: backend/Infrastructure/Security/SotoGomezTelesforo.Security.Service/Dockerfile
    ports:
      - 9093:80
      - 9094:443
    networks:
      - backend

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1234
    ports:
      - 1434:1433
    networks:
      - backend
networks:
  backend:
    name: backend
    driver: bridge

