#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["backend/Infrastructure/Security/SotoGomezTelesforo.Security.Service/SotoGomezTelesforo.Security.Service.csproj", "backend/Infrastructure/Security/SotoGomezTelesforo.Security.Service/"]
RUN dotnet restore "backend/Infrastructure/Security/SotoGomezTelesforo.Security.Service/SotoGomezTelesforo.Security.Service.csproj"
COPY . .
WORKDIR "/src/backend/Infrastructure/Security/SotoGomezTelesforo.Security.Service"
RUN dotnet build "SotoGomezTelesforo.Security.Service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SotoGomezTelesforo.Security.Service.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SotoGomezTelesforo.Security.Service.dll"]