// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SotoGomezTelesforo.Alumno.Service.Domain.School.Entities;

public partial class Course
{
    public Guid Id { get; set; }

    public string CourseName { get; set; }

    public string CourseDescription { get; set; }

    public virtual ICollection<Enrollment> Enrollments { get; set; } = new List<Enrollment>();
}