// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SotoGomezTelesforo.Alumno.Service.Domain.School.Entities;

public partial class Enrollment
{
    public Guid Id { get; set; }

    public Guid CourseId { get; set; }

    public Guid StudentId { get; set; }

    public DateTime EnrollmentDate { get; set; }

    public virtual Course Course { get; set; }

    public virtual Student Student { get; set; }
}