// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SotoGomezTelesforo.Alumno.Service.Domain.School.Entities;
using SotoGomezTelesforo.Alumno.Service.Intrastructure.Persistence.Contexts;
using System;
using System.Collections.Generic;

namespace SotoGomezTelesforo.Alumno.Service.Intrastructure.Persistence.Contexts.Configurations
{
    public partial class EnrollmentConfiguration : IEntityTypeConfiguration<Enrollment>
    {
        public void Configure(EntityTypeBuilder<Enrollment> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Enrollme__3214EC07C3F9CB90");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.EnrollmentDate).HasColumnType("datetime");

            entity.HasOne(d => d.Course).WithMany(p => p.Enrollments)
            .HasForeignKey(d => d.CourseId)
            .HasConstraintName("FK_Course_Student");

            entity.HasOne(d => d.Student).WithMany(p => p.Enrollments)
            .HasForeignKey(d => d.StudentId)
            .HasConstraintName("FK_Student_Course");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Enrollment> entity);
    }
}
